export const rolesHR = [
  {
    id: 1,
    first_name: "Irina",
    last_name: "McQuirk",
    role: "Project Manager",
    contact_no: "488-605-7813",
  },
  {
    id: 2,
    first_name: "Ethelda",
    last_name: "Busch",
    role: "Construction Worker",
    contact_no: "875-844-5826",
  },
  {
    id: 3,
    first_name: "Lem",
    last_name: "Garvie",
    role: "Electrician",
    contact_no: "278-737-1684",
  },
  {
    id: 4,
    first_name: "Zared",
    last_name: "Nottle",
    role: "Construction Manager",
    contact_no: "641-231-8606",
  },
  {
    id: 5,
    first_name: "Yettie",
    last_name: "Burlingham",
    role: "Construction Worker",
    contact_no: "454-313-5385",
  },
  {
    id: 6,
    first_name: "Bidget",
    last_name: "Barroux",
    role: "Engineer",
    contact_no: "189-700-0620",
  },
  {
    id: 7,
    first_name: "Padraig",
    last_name: "Terrell",
    role: "Surveyor",
    contact_no: "410-318-0493",
  },
  {
    id: 8,
    first_name: "Krissie",
    last_name: "Issakov",
    role: "Architect",
    contact_no: "771-504-1284",
  },
  {
    id: 9,
    first_name: "Amalea",
    last_name: "Haville",
    role: "Construction Foreman",
    contact_no: "185-555-9709",
  },
  {
    id: 10,
    first_name: "Lynnelle",
    last_name: "Czajkowska",
    role: "Engineer",
    contact_no: "597-393-8558",
  },
];

export const rolesDeveloper = [
  {
    id: 1,
    first_name: "Renaud",
    last_name: "Prestidge",
    role: "Engineer",
    contact_no: "968-168-5958",
  },
  {
    id: 2,
    first_name: "Maggi",
    last_name: "Riccardi",
    role: "Construction Manager",
    contact_no: "971-638-9854",
  },
  {
    id: 3,
    first_name: "Collin",
    last_name: "Baselli",
    role: "Construction Manager",
    contact_no: "430-727-6845",
  },
  {
    id: 4,
    first_name: "Merrick",
    last_name: "Whellans",
    role: "Construction Expeditor",
    contact_no: "865-568-5975",
  },
  {
    id: 5,
    first_name: "Linn",
    last_name: "Basile",
    role: "Estimator",
    contact_no: "947-746-2788",
  },
  {
    id: 6,
    first_name: "Daisey",
    last_name: "Caswell",
    role: "Construction Foreman",
    contact_no: "684-628-6110",
  },
  {
    id: 7,
    first_name: "Chane",
    last_name: "Witcombe",
    role: "Engineer",
    contact_no: "305-675-6062",
  },
  {
    id: 8,
    first_name: "Ferrell",
    last_name: "Stout",
    role: "Engineer",
    contact_no: "273-426-4731",
  },
  {
    id: 9,
    first_name: "Jone",
    last_name: "Kitney",
    role: "Estimator",
    contact_no: "183-673-9778",
  },
  {
    id: 10,
    first_name: "Ilka",
    last_name: "Severwright",
    role: "Supervisor",
    contact_no: "573-892-9709",
  },
];

export const rolesSales = [
  {
    id: 1,
    first_name: "Clyde",
    last_name: "Fenge",
    role: "Construction Foreman",
    contact_no: "362-928-9023",
  },
  {
    id: 2,
    first_name: "Nikola",
    last_name: "Beagles",
    role: "Construction Foreman",
    contact_no: "178-896-8646",
  },
  {
    id: 3,
    first_name: "Ardene",
    last_name: "Mahood",
    role: "Construction Expeditor",
    contact_no: "635-791-5069",
  },
  {
    id: 4,
    first_name: "Dorrie",
    last_name: "Santus",
    role: "Subcontractor",
    contact_no: "524-990-2186",
  },
  {
    id: 5,
    first_name: "Hinze",
    last_name: "Feehily",
    role: "Construction Foreman",
    contact_no: "577-483-6497",
  },
  {
    id: 6,
    first_name: "Barnett",
    last_name: "Scotfurth",
    role: "Engineer",
    contact_no: "319-193-6180",
  },
  {
    id: 7,
    first_name: "Heall",
    last_name: "Ballston",
    role: "Surveyor",
    contact_no: "173-462-5395",
  },
  {
    id: 8,
    first_name: "Eleanore",
    last_name: "Gannicleff",
    role: "Supervisor",
    contact_no: "964-745-1033",
  },
  {
    id: 9,
    first_name: "Janina",
    last_name: "Frossell",
    role: "Surveyor",
    contact_no: "735-186-8021",
  },
  {
    id: 10,
    first_name: "Mady",
    last_name: "Yallowley",
    role: "Engineer",
    contact_no: "404-736-2571",
  },
];
